### ISSUE TITLE
LICENSE issue

### ISSUE THREAD

**Issue by mherrb** [CNRS-DSI-Dev/mycore_wayf#1]
Hi, 

The README and DOC files claim that this code was written at SWITCH and refere to the LICENSE file for details.

But in the LICENSE file, only CNRS-DSI is listed as copyright owner and is different from the original file on SWITCH's forge: https://forge.switch.ch/redmine/projects/wayf/repository/entry/LICENSE 

It should probably be fixed to restore the original copyright notice. (If you did significant changes, you can add your own, but the original LICENSE doesn't grant you the right to remove the original one).

**Comment by sodetemplin** [comment]
Hi
Thanks for this issue, we will fix it within a few days. 
:-(

**Comment by ggambini** [comment]
Hi Matthieu,

I think, i overwrite original licence file when i was created git repo, oops. File was restored with right SWITCH copyright.

Best regard, Gilian.

edit: We only modifiy conf files or theming, we dont need to add CNRS copyright ;-)
